#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a9y18qlte

PRODUCT_COPY_FILES += \
    vendor/samsung/a9y18qlte/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/samsung/a9y18qlte/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/samsung/a9y18qlte/proprietary/product/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/epdg_apns_conf.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/epdg_apns_conf.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/eris.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/eris.conf \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/nvm_tlv.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv.bin \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/nvm_tlv_1.3.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_1.3.bin \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/nvm_tlv_2.1.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_2.1.bin \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/nvm_tlv_3.0.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_3.0.bin \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/nvm_tlv_3.2.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nvm_tlv_3.2.bin \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/rampatch_tlv.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv.img \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/rampatch_tlv_1.3.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_1.3.tlv \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/rampatch_tlv_2.1.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_2.1.tlv \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/rampatch_tlv_3.0.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_3.0.tlv \
    vendor/samsung/a9y18qlte/proprietary/system/etc/firmware/rampatch_tlv_3.2.tlv:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/rampatch_tlv_3.2.tlv \
    vendor/samsung/a9y18qlte/proprietary/system/etc/init/imsd.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/imsd.rc \
    vendor/samsung/a9y18qlte/proprietary/system/etc/init/init.rilepdg.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.rilepdg.rc \
    vendor/samsung/a9y18qlte/proprietary/system/etc/init/multiclientd.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/multiclientd.rc \
    vendor/samsung/a9y18qlte/proprietary/system/etc/mapconprovider.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/mapconprovider.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/nfcee_access.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/nfcee_access.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/audiosphere.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/com.qti.location.sdk.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.qti.location.sdk.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/com.qualcomm.location.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.qualcomm.location.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/com.qualcomm.qti.imscmservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.qualcomm.qti.imscmservice.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/embms.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/embms.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/epdgmanager_library.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/epdgmanager_library.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/imsmanager_library.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/imsmanager_library.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/izat.xt.srv.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/izat.xt.srv.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/privapp-permissions-com.qualcomm.location.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/privapp-permissions-com.sec.epdg.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.sec.epdg.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/privapp-permissions-com.sec.ims.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.sec.ims.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/privapp-permissions-com.sec.imsservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.sec.imsservice.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/rcsopenapi_library.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/rcsopenapi_library.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/svemanager_library.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/svemanager_library.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/permissions/vsimservice_library.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/vsimservice_library.xml \
    vendor/samsung/a9y18qlte/proprietary/system/etc/strongswan.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/strongswan.conf \
    vendor/samsung/a9y18qlte/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/SoundBoosterParam.txt:$(TARGET_COPY_OUT_VENDOR)/etc/SoundBoosterParam.txt \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Bluetooth_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/General_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Global_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Handset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Hdmi_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Headset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Speaker_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODM/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/workspaceFile.qwsp \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Bluetooth_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/General_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Global_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Handset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Hdmi_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Headset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/Speaker_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/ODX/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODX/workspaceFile.qwsp \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audio_configs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_configs.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audio_effects_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects_sec.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audio_policy_configuration_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_sec.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes_sec.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/A08QL_s5k4hayx_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/A08QL_s5k4hayx_module_info.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/C13QL_s5k3m3_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/C13QL_s5k3m3_module_info.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/D24QS_imx576_front_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/D24QS_imx576_front_module_info.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/E24QS_imx576_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/E24QS_imx576_module_info.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/S05QL_s5k5e9yx_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/S05QL_s5k5e9yx_module_info.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/imx576_d24qs_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx576_d24qs_chromatix.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/imx576_e24qs_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx576_e24qs_chromatix.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/s5k3m3_c13ql_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m3_c13ql_chromatix.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/s5k4hayx_a08ql_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4hayx_a08ql_chromatix.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/camera/s5k5e9yx_s05ql_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e9yx_s05ql_chromatix.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/floating_feature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/floating_feature.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/hostapd/hostapd_default.conf:$(TARGET_COPY_OUT_VENDOR)/etc/hostapd/hostapd_default.conf \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.widevine.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/android.hardware.sensors@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/android.hardware.usb@1.1-service.wahoo.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.1-service.wahoo.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/init.vendor.rilchip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilchip.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/ipacm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/nxp.android.hardware.nfc@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nxp.android.hardware.nfc@1.1-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/pa_daemon_qsee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pa_daemon_qsee.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/secure_storage_daemon_qsee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/secure_storage_daemon_qsee.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.hardware.fstman@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.fstman@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.samsung.hardware.biometrics.fingerprint@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.biometrics.fingerprint@3.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.samsung.hardware.camera.provider@3.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.camera.provider@3.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.samsung.hardware.miscpower@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.miscpower@2.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.samsung.hardware.tlc.ucm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.tlc.ucm@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.samsung.hardware.wifi@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.wifi@2.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.teeregistry@1.0-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/wifi.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/wifi_qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_qcom.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/init/wsm-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wsm-service.rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_ac4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_ac4.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_ddp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_ddp.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_sec_ape.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sec_ape.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_sec_primary.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sec_primary.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_sec_qcp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sec_qcp.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_sec_secondary.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sec_secondary.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/media_codecs_sec_video_primary.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_sec_video_primary.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/nfc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/libnfc-nxp_RF.conf \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/permissions/com.android.nfc_extras.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.android.nfc_extras.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/permissions/com.nxp.mifare.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.nxp.mifare.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/playback_record_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/playback_record_audio_policy_configuration.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/plmn_delta_usacdma.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usacdma.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/process_authenticator/pa_config:$(TARGET_COPY_OUT_VENDOR)/etc/process_authenticator/pa_config \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/public.libraries.txt.backup:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt.backup \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/sec_config_oem:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config_oem \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/snap_gpu_kernel_32.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_32.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/snap_gpu_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/snap_gpu_kernel_64.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/somxreg.conf:$(TARGET_COPY_OUT_VENDOR)/etc/somxreg.conf \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9330.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9330.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9335.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9335.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9340.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9340.xml \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/wifi/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_cfg.ini \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/wlan_common_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_common_rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/wlan_vendor_rc:$(TARGET_COPY_OUT_VENDOR)/etc/wlan_vendor_rc \
    vendor/samsung/a9y18qlte/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/Tfa9872.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9872.cnt \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a508_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.b00 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a508_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.b01 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a508_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.b02 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a508_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.elf \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a508_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a508_zap.mdt \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/dbmd4_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd4_va_fw.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/msadp:$(TARGET_COPY_OUT_VENDOR)/firmware/msadp \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/nfc/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/libpn553_fw.so \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/wlan/qca_cld/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/wlan/qca_cld/grippower.info:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/grippower.info \
    vendor/samsung/a9y18qlte/proprietary/vendor/firmware/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp.mbn \
    vendor/samsung/a9y18qlte/proprietary/vendor/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn.prototxt \
    vendor/samsung/a9y18qlte/proprietary/vendor/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_classifier/aic_classifier_cnn_light.caffemodel \
    vendor/samsung/a9y18qlte/proprietary/vendor/saiv/image_understanding/db/aic_detector/aic_detector_cnn.prototxt:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_detector/aic_detector_cnn.prototxt \
    vendor/samsung/a9y18qlte/proprietary/vendor/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel:$(TARGET_COPY_OUT_VENDOR)/saiv/image_understanding/db/aic_detector/aic_detector_cnn_light.caffemodel

PRODUCT_PACKAGES += \
    com.qualcomm.qti.ant@1.0 \
    fm_helium \
    libFileMux \
    libfactoryutil \
    libfloatingfeature \
    libfm-hci \
    libmdf \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libomission_avoidance \
    libpacm_client \
    libsdm-disp-apis \
    libsecaudiocoreutils \
    libsecaudioeventutils \
    libsecnativefeature \
    libsecril-client \
    libsecure_storage \
    libsemnativecarrierfeature \
    vendor.qti.hardware.fm@1.0 \
    libAudioFWInterface \
    libAudioTranscoder \
    libPSI \
    libRecorder \
    libSRTP \
    libSTE \
    libSamsungAPVoiceEngine \
    libaptX_encoder \
    libaresdns \
    libcharon \
    libcurl2 \
    liberis_charon \
    liberis_simaka \
    liberis_strongswan \
    libevs_float \
    liblocationservice_jni \
    libmediarelayengine \
    libnativecfms \
    libresampler_ims \
    librtp \
    librtppayload \
    libsamsung_videoengine_9_0 \
    libsavscmn \
    libsec-ims \
    libstrongswan \
    libsvejni \
    libsveservice \
    libvad \
    libxt_native \
    vendor.samsung.hardware.radio.bridge@2.0 \
    android.hardware.camera.provider@2.4-legacy \
    com.qualcomm.qti.ant@1.0_vendor \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.uceservice@2.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    activity_recognition.sdm660 \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gnss@2.0-impl-qti \
    android.hardware.sensors@1.0-impl \
    audio.sec_primary.default \
    com.qualcomm.qti.ant@1.0-impl \
    fingerprint.default \
    gralloc.sdm660 \
    hwcomposer.sdm660 \
    memtrack.sdm660 \
    power.qcom \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.iop@2.0-impl \
    vendor.samsung.hardware.camera.provider@3.0-impl \
    vendor.samsung.hardware.gnss@2.0-impl-sec \
    vulkan.sdm660 \
    libAlacSwDec \
    libApeSwDec \
    libC2D2 \
    libCB \
    libDLInterface.camera.samsung \
    libFlacSwDec \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libI420colorconvert \
    libMcClient \
    libOpenCL \
    libOpenCv.camera.samsung \
    libQSEEComAPI \
    libRSDriver_adreno \
    libSecureUILib \
    libStDrvInt \
    libSubSystemShutdown \
    libUBWC \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libarac \
    libaudcal \
    libaudioalsa \
    libaudioparsers \
    libbase64 \
    libbatching \
    libbauthserver \
    libbauthtzcommon \
    libbccQTI \
    libbt-hidlclient \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libconfigdb \
    libcpion \
    libdataitems \
    libdiag \
    libdiagjni \
    libdisp-aba \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libdsi_netctrl \
    libdsutils \
    libegis_fp_normal_sensor_test \
    libfastcrc \
    libfastcvadsp_stub \
    libfastcvopt \
    libfloatingfeature_vendor \
    libgarden \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgdtap \
    libgeofencing \
    libgf_in_system_lib \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpu_tonemapper \
    libgpustats \
    libgrallocutils \
    libgsl \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdr_tm \
    libhifills \
    libhifills_interface \
    libhypermotion_core \
    libhypermotion_interface \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdf_vendor \
    libmdmdetect \
    libmdsprpc \
    libmm-color-convertor \
    libmm-hdcpmgr \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_cac3_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmosal_proprietary \
    libmmsw_detail_enhancement \
    libmmsw_math \
    libmmsw_opencl \
    libmmsw_platform \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    liboemaids_vendor \
    liboemcrypto \
    libpa \
    libpadm \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperipheral_client \
    libprofileparamstorage \
    libpvr \
    libqcmaputils \
    libqdMetaData \
    libqdi \
    libqdma_file_agent \
    libqdp \
    libqdutils \
    libqfp_sensortest \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqservice \
    libqsocket \
    libqti-iopd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libqtigef \
    libreference-ril \
    libremosaic_daemon \
    libremosaiclib \
    libril \
    librilutils \
    librmnetctl \
    librmp \
    librpmb \
    librs_adreno \
    librs_adreno_sha1 \
    libsaiv_BeautySolutionVideo \
    libsavsac \
    libsavscmn_vendor \
    libsavsvc \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsec-ril-dsds \
    libsec-ril \
    libsecaudiocoreutils_vendor \
    libsecaudioinfo \
    libsecnativefeature_vendor \
    libsecure_storage_vendor \
    libsecureui \
    libsecureui_svcsock \
    libsensor1 \
    libsensor_reg \
    libsensorlistener \
    libsensorndkbridge \
    libsi \
    libsnaace \
    libsnamrnb \
    libsnamrwb \
    libsnap_caffe \
    libsnap_caffe_wrapper \
    libsnap_compute \
    libsnap_compute_wrapper \
    libsnap_vndk \
    libsns_low_lat_stream_stub \
    libsomx263dsw \
    libsomx264dsw \
    libsomxaacd \
    libsomxadpcmd \
    libsomxamrd \
    libsomxcmn \
    libsomxcore_vendor \
    libsomxflacd \
    libsomxhevcdsw \
    libsomxmp3d \
    libsomxmp43d \
    libsomxmp4vdsw \
    libsomxnaace \
    libsomxvc1dsw \
    libsomxvp8d \
    libsomxwmad \
    libsomxwmv7d \
    libsomxwmv8d \
    libssd \
    libstagefright_soft_qtiflacdec \
    libstreamparser \
    libsubsystem_control \
    libswldc_capture_core.camera.samsung \
    libsxqk \
    libsynaFpSensorTestNwd \
    libsynergy_loc_api \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libtzdrmgenprov \
    libuniplugin \
    libvdis_core \
    libvdis_interface \
    libvideobeauty_interface \
    libvideoutils \
    libvkmanager_vendor \
    libvndsecril-client \
    libvpphvx \
    libvpplibrary \
    libxcv.camera.samsung \
    libxml \
    libxtadapter \
    sensor_calibrate \
    sensors.grip \
    sensors.ssc \
    libasphere \
    libaudioeffectoffload \
    libqcbassboost \
    libqcompostprocbundle \
    libqcomvisualizer \
    libqcomvoiceprocessing \
    libqcreverb \
    libqcvirt \
    libswdap \
    libvolumelistener \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.postproc@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.latency@2.0 \
    vendor.qti.voiceprint@1.0 \
    vendor.samsung.camera.device@1.0-impl \
    vendor.samsung.camera.device@4.0-impl \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.camera.device@1.0 \
    vendor.samsung.hardware.camera.device@4.0 \
    vendor.samsung.hardware.camera.provider@3.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.radio.bridge@2.0_vendor \
    vendor.samsung.hardware.radio.channel@2.0 \
    vendor.samsung.hardware.radio@2.0 \
    vendor.samsung.hardware.security.proca@2.0 \
    vendor.samsung.hardware.tlc.ucm@1.0-impl \
    vendor.samsung.hardware.tlc.ucm@1.0 \
    android.hardware.camera.provider@2.5-legacy \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-impl \
    camera.device@3.5-impl \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    audio.primary.sdm660 \
    camera.sdm660 \
    sound_trigger.primary.sdm660 \
    libHMT \
    lib_SamsungRec_06005 \
    lib_SoundAlive_3DPosition_ver202 \
    lib_SoundAlive_SRC384_ver320 \
    lib_soundaliveresampler \
    libactuator_dw9808 \
    libactuator_dw9808_sub \
    libadm \
    libadpcmdec \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libaudio_log_utils \
    libaudio_soundtrigger \
    libchromatix_imx576_d24qs_3rd_preview_high_cpp \
    libchromatix_imx576_d24qs_common \
    libchromatix_imx576_d24qs_default_video_3a \
    libchromatix_imx576_d24qs_hfr_120_3a \
    libchromatix_imx576_d24qs_hfr_120_cpp \
    libchromatix_imx576_d24qs_hfr_120_isp \
    libchromatix_imx576_d24qs_liveshot_cpp \
    libchromatix_imx576_d24qs_liveshot_isp \
    libchromatix_imx576_d24qs_mode_effect_video_3a \
    libchromatix_imx576_d24qs_mode_face_unlock_3a \
    libchromatix_imx576_d24qs_mode_face_unlock_cpp \
    libchromatix_imx576_d24qs_mode_face_unlock_isp \
    libchromatix_imx576_d24qs_mode_hdr_auto_3a \
    libchromatix_imx576_d24qs_mode_hdr_auto_cpp \
    libchromatix_imx576_d24qs_mode_hdr_auto_isp \
    libchromatix_imx576_d24qs_mode_hdr_on_3a \
    libchromatix_imx576_d24qs_mode_hdr_on_cpp \
    libchromatix_imx576_d24qs_mode_hdr_on_isp \
    libchromatix_imx576_d24qs_mode_wide_selfie_3a \
    libchromatix_imx576_d24qs_mode_wide_selfie_cpp \
    libchromatix_imx576_d24qs_mode_wide_selfie_isp \
    libchromatix_imx576_d24qs_preview_color_iris_isp \
    libchromatix_imx576_d24qs_preview_high_cpp \
    libchromatix_imx576_d24qs_preview_high_isp \
    libchromatix_imx576_d24qs_preview_low_cpp \
    libchromatix_imx576_d24qs_preview_low_isp \
    libchromatix_imx576_d24qs_remosaic_hdr_auto_cpp \
    libchromatix_imx576_d24qs_remosaic_hdr_auto_isp \
    libchromatix_imx576_d24qs_remosaic_hdr_on_cpp \
    libchromatix_imx576_d24qs_remosaic_hdr_on_isp \
    libchromatix_imx576_d24qs_snapshot_high_cpp \
    libchromatix_imx576_d24qs_snapshot_high_isp \
    libchromatix_imx576_d24qs_snapshot_high_lls_cpp \
    libchromatix_imx576_d24qs_snapshot_low_cpp \
    libchromatix_imx576_d24qs_snapshot_low_isp \
    libchromatix_imx576_d24qs_snapshot_remosaic_cpp \
    libchromatix_imx576_d24qs_snapshot_remosaic_isp \
    libchromatix_imx576_d24qs_sw_post_proc_remosaic \
    libchromatix_imx576_d24qs_sw_post_proc_tetra \
    libchromatix_imx576_d24qs_video_high_cpp \
    libchromatix_imx576_d24qs_video_high_isp \
    libchromatix_imx576_d24qs_video_low_cpp \
    libchromatix_imx576_d24qs_video_low_isp \
    libchromatix_imx576_d24qs_vt_15fps_3a \
    libchromatix_imx576_d24qs_vt_24fps_3a \
    libchromatix_imx576_d24qs_vt_30fps_3a \
    libchromatix_imx576_d24qs_vt_7fps_3a \
    libchromatix_imx576_d24qs_vt_high_cpp \
    libchromatix_imx576_d24qs_vt_high_isp \
    libchromatix_imx576_d24qs_vt_low_cpp \
    libchromatix_imx576_d24qs_vt_low_isp \
    libchromatix_imx576_d24qs_zsl_preview_3a \
    libchromatix_imx576_e24qs_3rd_preview_high_3a \
    libchromatix_imx576_e24qs_3rd_preview_high_cpp \
    libchromatix_imx576_e24qs_3rd_preview_high_isp \
    libchromatix_imx576_e24qs_4k_preview_3a \
    libchromatix_imx576_e24qs_4k_video_3a \
    libchromatix_imx576_e24qs_common \
    libchromatix_imx576_e24qs_hfr_120_3a \
    libchromatix_imx576_e24qs_hfr_120_cpp \
    libchromatix_imx576_e24qs_hfr_120_isp \
    libchromatix_imx576_e24qs_liveshot_cpp \
    libchromatix_imx576_e24qs_liveshot_isp \
    libchromatix_imx576_e24qs_mode_effect_video_3a \
    libchromatix_imx576_e24qs_mode_hdr_auto_3a \
    libchromatix_imx576_e24qs_mode_hdr_auto_cpp \
    libchromatix_imx576_e24qs_mode_hdr_auto_isp \
    libchromatix_imx576_e24qs_mode_hdr_on_3a \
    libchromatix_imx576_e24qs_mode_hdr_on_cpp \
    libchromatix_imx576_e24qs_mode_hdr_on_isp \
    libchromatix_imx576_e24qs_mode_iso_cpp \
    libchromatix_imx576_e24qs_mode_iso_isp \
    libchromatix_imx576_e24qs_mode_lls_cpp \
    libchromatix_imx576_e24qs_mode_motion_lls_cpp \
    libchromatix_imx576_e24qs_mode_night_3a \
    libchromatix_imx576_e24qs_mode_night_cpp \
    libchromatix_imx576_e24qs_mode_night_isp \
    libchromatix_imx576_e24qs_mode_outfocus_3a \
    libchromatix_imx576_e24qs_mode_outfocus_cpp \
    libchromatix_imx576_e24qs_mode_outfocus_isp \
    libchromatix_imx576_e24qs_mode_panorama_3a \
    libchromatix_imx576_e24qs_mode_panorama_cpp \
    libchromatix_imx576_e24qs_mode_panorama_isp \
    libchromatix_imx576_e24qs_mode_slowmotion_3a \
    libchromatix_imx576_e24qs_mode_sports_3a \
    libchromatix_imx576_e24qs_mode_sports_cpp \
    libchromatix_imx576_e24qs_mode_sports_isp \
    libchromatix_imx576_e24qs_preview_cpp \
    libchromatix_imx576_e24qs_preview_isp \
    libchromatix_imx576_e24qs_remosaic_hdr_auto_cpp \
    libchromatix_imx576_e24qs_remosaic_hdr_auto_isp \
    libchromatix_imx576_e24qs_remosaic_hdr_on_cpp \
    libchromatix_imx576_e24qs_remosaic_hdr_on_isp \
    libchromatix_imx576_e24qs_snapshot_cpp \
    libchromatix_imx576_e24qs_snapshot_isp \
    libchromatix_imx576_e24qs_snapshot_remosaic_cpp \
    libchromatix_imx576_e24qs_snapshot_remosaic_isp \
    libchromatix_imx576_e24qs_sw_post_proc_remosaic \
    libchromatix_imx576_e24qs_sw_post_proc_tetra \
    libchromatix_imx576_e24qs_video_4k_cpp \
    libchromatix_imx576_e24qs_video_cpp \
    libchromatix_imx576_e24qs_video_hd_isp \
    libchromatix_imx576_e24qs_video_isp \
    libchromatix_imx576_e24qs_vt_24fps_3a \
    libchromatix_imx576_e24qs_zsl_preview_3a \
    libchromatix_imx576_e24qs_zsl_video_15fps_3a \
    libchromatix_imx576_e24qs_zsl_video_3a \
    libchromatix_s5k3m3_c13ql_4k_preview_3a \
    libchromatix_s5k3m3_c13ql_4k_video_3a \
    libchromatix_s5k3m3_c13ql_common \
    libchromatix_s5k3m3_c13ql_liveshot_cpp \
    libchromatix_s5k3m3_c13ql_mode_effect_video_3a \
    libchromatix_s5k3m3_c13ql_mode_hdr_auto_3a \
    libchromatix_s5k3m3_c13ql_mode_hdr_auto_cpp \
    libchromatix_s5k3m3_c13ql_mode_hdr_auto_isp \
    libchromatix_s5k3m3_c13ql_mode_hdr_on_3a \
    libchromatix_s5k3m3_c13ql_mode_hdr_on_cpp \
    libchromatix_s5k3m3_c13ql_mode_hdr_on_isp \
    libchromatix_s5k3m3_c13ql_mode_lls_cpp \
    libchromatix_s5k3m3_c13ql_mode_motion_lls_cpp \
    libchromatix_s5k3m3_c13ql_preview_cpp \
    libchromatix_s5k3m3_c13ql_snapshot_cpp \
    libchromatix_s5k3m3_c13ql_snapshot_isp \
    libchromatix_s5k3m3_c13ql_sw_post_proc \
    libchromatix_s5k3m3_c13ql_video_4k_cpp \
    libchromatix_s5k3m3_c13ql_video_cpp \
    libchromatix_s5k3m3_c13ql_video_isp \
    libchromatix_s5k3m3_c13ql_zsl_preview_3a \
    libchromatix_s5k3m3_c13ql_zsl_video_3a \
    libchromatix_s5k4hayx_a08ql_4k_preview_3a \
    libchromatix_s5k4hayx_a08ql_4k_video_3a \
    libchromatix_s5k4hayx_a08ql_common \
    libchromatix_s5k4hayx_a08ql_hfr_120_3a \
    libchromatix_s5k4hayx_a08ql_hfr_120_cpp \
    libchromatix_s5k4hayx_a08ql_hfr_120_isp \
    libchromatix_s5k4hayx_a08ql_liveshot_cpp \
    libchromatix_s5k4hayx_a08ql_mode_effect_video_3a \
    libchromatix_s5k4hayx_a08ql_mode_hdr_auto_3a \
    libchromatix_s5k4hayx_a08ql_mode_hdr_auto_cpp \
    libchromatix_s5k4hayx_a08ql_mode_hdr_auto_isp \
    libchromatix_s5k4hayx_a08ql_mode_hdr_on_3a \
    libchromatix_s5k4hayx_a08ql_mode_hdr_on_cpp \
    libchromatix_s5k4hayx_a08ql_mode_hdr_on_isp \
    libchromatix_s5k4hayx_a08ql_mode_lls_cpp \
    libchromatix_s5k4hayx_a08ql_mode_motion_lls_cpp \
    libchromatix_s5k4hayx_a08ql_mode_panorama_3a \
    libchromatix_s5k4hayx_a08ql_mode_panorama_cpp \
    libchromatix_s5k4hayx_a08ql_mode_panorama_isp \
    libchromatix_s5k4hayx_a08ql_preview_cpp \
    libchromatix_s5k4hayx_a08ql_snapshot_cpp \
    libchromatix_s5k4hayx_a08ql_snapshot_isp \
    libchromatix_s5k4hayx_a08ql_sw_post_proc \
    libchromatix_s5k4hayx_a08ql_video_4k_cpp \
    libchromatix_s5k4hayx_a08ql_video_cpp \
    libchromatix_s5k4hayx_a08ql_video_isp \
    libchromatix_s5k4hayx_a08ql_zsl_preview_3a \
    libchromatix_s5k4hayx_a08ql_zsl_video_3a \
    libchromatix_s5k5e9yx_s05ql_4k_preview_3a \
    libchromatix_s5k5e9yx_s05ql_4k_video_3a \
    libchromatix_s5k5e9yx_s05ql_common \
    libchromatix_s5k5e9yx_s05ql_liveshot_cpp \
    libchromatix_s5k5e9yx_s05ql_mode_outfocus_3a \
    libchromatix_s5k5e9yx_s05ql_mode_outfocus_cpp \
    libchromatix_s5k5e9yx_s05ql_mode_outfocus_isp \
    libchromatix_s5k5e9yx_s05ql_preview_cpp \
    libchromatix_s5k5e9yx_s05ql_snapshot_cpp \
    libchromatix_s5k5e9yx_s05ql_snapshot_isp \
    libchromatix_s5k5e9yx_s05ql_sw_post_proc \
    libchromatix_s5k5e9yx_s05ql_video_4k_cpp \
    libchromatix_s5k5e9yx_s05ql_video_cpp \
    libchromatix_s5k5e9yx_s05ql_video_isp \
    libchromatix_s5k5e9yx_s05ql_zsl_preview_3a \
    libchromatix_s5k5e9yx_s05ql_zsl_video_3a \
    libcppf \
    libdepthmapwrapper \
    libdrc \
    libdsd2pcm \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_dw9808_eeprom \
    libmmcamera_dw9808_sub_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_gt24c64a_eeprom \
    libmmcamera_gt24p128c_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx258_gt24c16_eeprom \
    libmmcamera_imx258_gt24c32_eeprom \
    libmmcamera_imx258_mono_gt24c32_eeprom \
    libmmcamera_imx576 \
    libmmcamera_imx576_front \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_lsi_s5k5e9yx_otp_eeprom \
    libmmcamera_m24128s_eeprom \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_m24c64x_eeprom \
    libmmcamera_ofilm_ohs0443_ov12a10_eeprom \
    libmmcamera_ofilm_ohs0443_ov13880_eeprom \
    libmmcamera_onsemi_cat24c16_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_onsemi_cat24c32_imx362_eeprom \
    libmmcamera_onsemi_cat24c64_eeprom \
    libmmcamera_onsemi_cat24s128_eeprom \
    libmmcamera_onsemi_cat24s128_sub_eeprom \
    libmmcamera_ov4688_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_qtech_f3l8yam_eeprom \
    libmmcamera_qtech_f5670bq_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_s5k3m3 \
    libmmcamera_s5k4hayx \
    libmmcamera_s5k5e9yx \
    libmmcamera_sony_imx214_eeprom \
    libmmcamera_sony_imx298_eeprom \
    libmmcamera_sony_imx378_eeprom \
    libmmcamera_sonyimx135_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sunny_8865_eeprom \
    libmmcamera_sunny_gt24c64_imx298_eeprom \
    libmmcamera_sunny_gt24c64_s5k2l7_eeprom \
    libmmcamera_sunny_gt24c64_s5k2l7sx_eeprom \
    libmmcamera_sunny_gt24c64a_imx362_eeprom \
    libmmcamera_sunny_gt24c64a_imx376_eeprom \
    libmmcamera_sunny_ov13855_eeprom \
    libmmcamera_sunny_q13v06k_eeprom \
    libmmcamera_sunny_q5v41b_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_videobeauty \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    librecordalive \
    libsamsungVoipResampler \
    libstagefright_bufferqueue_helper_vendor \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libstagefright_soft_g711dec \
    libstagefright_soft_rawdec \
    libstagefright_soft_vorbisdec \
    libsurround_3mic_proc \
    libsysmon_cdsp_skel \
    libvqzip \
    libwifi-hal \
    libwvhidl \
    libwvdrmengine \
    libaudiosaplus_sec \
    libgearvr \
    libmysound \
    libmyspace \
    libplaybackrecorder \
    libsamsungSoundbooster_plus \
    vendor.qti.hardware.audiohalext@1.0 \
    gatekeeper.mdfpp \
    keystore.mdfpp \
    libdsms_vendor \
    libhal.wsm.samsung \
    libipanat \
    libkeymaster2_mdfpp \
    libkeymaster_helper_vendor \
    libnlnetmgr \
    liboffloadhal \
    libthermalioctl \
    libucsengine \
    libwsmd_functions \
    nfc_nci_nxp \
    vendor.nxp.nxpnfc@1.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.samsung.frameworks.security.dsms@1.0_vendor \
    vendor.samsung.hardware.biometrics.fingerprint@3.0 \
    vendor.samsung.hardware.health@1.0 \
    vendor.samsung.hardware.miscpower@2.0 \
    vendor.samsung.hardware.security.securestorage@3.0 \
    vendor.samsung.hardware.wifi.hostapd@2.0 \
    vendor.samsung.hardware.wifi.supplicant@2.0 \
    vendor.samsung.hardware.wifi@2.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.teeregistry@1.0 \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_800h_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libscveBlobDescriptor_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_low_lat_stream_skel \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    libdiag_system \
    vendor.qti.data.factory@1.0 \
    ImsSettings \
    sveservice \
    EpdgService \
    HotwordEnrollmentOKGoogleExTL3210 \
    ImsTelephonyService \
    imsservice \
    TimeService \
    EpdgManager \
    audiosphere \
    com.qti.location.sdk \
    embmslibrary \
    imsmanager \
    izat.xt.srv \
    qcrilhook \
    rcsopenapi \
    svemanager \
    tcmclient \
    vsimmanager \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    dpmapi \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V2.0-java \
    vendor.qti.data.factory-V2.1-java \
    privapp-permissions-qti.xml \
    qti_whitelist.xml \
    libnfc-nci.conf \
    libnfc-nxp.conf \
    android.hardware.gnss@2.0-service-qti.xml \
    vendor.qti.gnss@3.0-service.xml \
    charon \
    connfwexe \
    eris \
    imsd \
    multiclientd \
    smdexe \
    ATFWD-daemon \
    PktRspTest \
    StoreKeybox \
    adpl \
    adsprpcd \
    athdiag \
    audioflacapp \
    cdsprpcd \
    cnss-daemon \
    diag_callback_sample \
    diag_dci_sample \
    diag_klog \
    diag_mdlog \
    diag_socket_log \
    diag_uart_log \
    e_loop \
    energy-awareness \
    factory.adsp \
    fmconfig \
    fmfactorytest \
    fmfactorytestserver \
    fstman \
    hal_proxy_daemon \
    hdcp1prov \
    hdcp2p2prov \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.2-service.widevine \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.sensors@1.0-service \
    android.hardware.usb@1.1-service.wahoo \
    macloader \
    mfgloader \
    nxp.android.hardware.nfc@1.1-service \
    rild \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.perf@2.0-service \
    vendor.qti.hardware.qdutils_disp@1.0-service-qti \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.samsung.hardware.biometrics.fingerprint@3.0-service \
    vendor.samsung.hardware.camera.provider@3.0-service \
    vendor.samsung.hardware.miscpower@2.0-service \
    vendor.samsung.hardware.tlc.ucm@1.0-service \
    vendor.samsung.hardware.wifi@2.0-service \
    vendor.trustonic.tee@1.0-service \
    vendor.trustonic.teeregistry@1.0-service \
    ipacm \
    ipacm-diag \
    irsc_util \
    loc_launcher \
    lowi-server \
    mcDriverDaemon \
    mm-qcamera-app \
    mm-qcamera-daemon \
    mm-qjpeg-dec-test \
    mm-qjpeg-enc-test \
    mm-qomx-idec-test \
    mm-qomx-ienc-test \
    netmgrd \
    pd-mapper \
    pktlogconf \
    pm-proxy \
    pm-service \
    qjpeg-dma-test \
    qrtr-ns \
    qseecom_sample_client \
    qseecomd \
    rmt_storage \
    secril_config_svc \
    secure_storage_daemon \
    secure_ui_sample_client \
    sensors.qti \
    sigma_dut \
    spectraltool \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    tbaseLoader \
    test_diag \
    test_module_pproc \
    tftp_server \
    thermal-engine \
    time_daemon \
    vendor.samsung.hardware.security.proca@2.0-service \
    vendor.samsung.hardware.security.wsm@1.0-service \
    vendor_cmd_tool \
    wvkprov \
    xtra-daemon
