#!/usr/bin/env python3
"""Generate SamsungImsHelper's XCAP APN table from Samsung CSC customer.xml files.

Usage: gen_xcap_apns.py <out xcap_apns.xml> <customer.xml>...

The shipped table is generated from the 107 regional CSCs of the Galaxy S26
(customer.xml under unica/mods/csc/optics/configs/carriers of
ExtremeROM-Revived-S26, branch sixteen).

Android 10's APN list has no XCAP APNs, and the IMS stack sets up a PDN on
the SIM's XCAP APN for call forwarding, call waiting and call barring over
Ut. A CSC names each network's XCAP APN profile in
ProfileHandle/ProfXCAP; the profile's NetworkName maps to MCCMNCs through
NetworkInfo. Networks told apart by SPN, GID or IMSI subset (MVNOs on a
host network's MCCMNC) are left out, as the helper matches on MCCMNC only.
An MCCMNC already taken by an earlier file or network keeps that entry.
"""

import re
import sys
import xml.etree.ElementTree as ET
from xml.sax.saxutils import quoteattr

SUBSET_TAGS = ('SPCode', 'SPName', 'SubsetCode', 'GID1', 'GID2', 'IMSI')


def text(el, tag):
    v = el.findtext(tag)
    return v.strip() if v else ''


def parse(path):
    root = ET.fromstring(re.sub(r'<\?xml[^>]*\?>', '', open(path, encoding='utf-8').read()))
    codes = {}
    for ni in root.iter('NetworkInfo'):
        if any(ni.find(t) is not None for t in SUBSET_TAGS):
            continue
        name, mccmnc = text(ni, 'NetworkName'), text(ni, 'MCCMNC')
        if name and re.fullmatch(r'\d{5,6}', mccmnc):
            codes.setdefault(name, []).append(mccmnc)
    profiles = {}
    for p in root.iter('Profile'):
        apn = p.findtext('PSparam/APN')
        if apn:
            profiles[(text(p, 'NetworkName'), text(p, 'ProfileName'))] = apn.strip()
    for h in root.iter('ProfileHandle'):
        name, prof = text(h, 'NetworkName'), text(h, 'ProfXCAP')
        apn = profiles.get((name, prof))
        if not prof or not apn:
            continue
        label = prof if prof.lower() != apn.lower() else name + ' XCAP'
        for mccmnc in codes.get(name, []):
            yield mccmnc, label, apn


def main(out, inputs):
    table = {}
    for path in inputs:
        for mccmnc, name, apn in parse(path):
            table.setdefault(mccmnc, (name, apn))
    with open(out, 'w') as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n')
        f.write('<!-- Generated by vendor/samsung/a9y18qlte/tools/imsservice/'
                'gen_xcap_apns.py. Do not edit. -->\n')
        f.write('<xcap-apns>\n')
        for mccmnc in sorted(table):
            name, apn = table[mccmnc]
            f.write('    <apn numeric=%s name=%s apn=%s />\n'
                    % (quoteattr(mccmnc), quoteattr(name), quoteattr(apn)))
        f.write('</xcap-apns>\n')
    print('%d XCAP APNs' % len(table))


if __name__ == '__main__':
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2:])
