#!/usr/bin/env python3
"""Generate a CSC customer.xml for com.sec.imsservice from Samsung's switch table.

Usage: gen_csc_from_imsswitch.py <imsswitch.json> <mnomap.json> <Mno.smali> <output>
           [<CarrierConfig vendor.xml> <epdg_apns_conf.xml>]

This imsservice only takes its per-carrier IMS switches (EnableIMS,
EnableVoLTE, ...) from a CSC customer.xml; without one it turns VoLTE off.
Newer Samsung IMS builds keep these switches in the app itself
(res/raw/imsswitch.json). This turns that table into a customer.xml so the
switches do not depend on the phone's own CSC on /odm.

- One Setting per carrier with enableIms and enableServiceVolte that the
  imsservice code knows (Mno.smali), matched by plain MCCMNC from mnomap.json;
  MVNOs on the same MCCMNC match their host network's entry.
- VoLTE on. The voice domain preference on LTE is left out, so imsservice
  takes it from globalsettings.json like newer releases do; they no longer read
  it from the CSC.
- VoWiFi on where the table has enableServiceVowifi. Video calls and SMS over
  IMS stay off: untested on this device.
- Voice/SS/USSD/emergency domains are left out, so imsservice uses its own
  per-carrier globalsettings.json values.

With a CarrierConfig vendor.xml, its VoWiFi section is regenerated for the same
carriers, on their MCC/MNC: Wi-Fi Calling available, so the framework offers it
exactly where imsservice does, with the switch and preferred mode that the
carrier's <vowifi> entry in epdg_apns_conf.xml (or its default entry) gives
EpdgService. Samsung modes without a framework equivalent leave the mode at the
framework default.
"""

import os
import re
from xml.sax.saxutils import quoteattr
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jsonc import load  # noqa: E402


def known_mnos(smali_path):
    smali = open(smali_path).read()
    names = set()
    for block in re.findall(r'new-instance v\d+, Lcom/sec/internal/ims/util/Mno;(.*?)sput-object',
                            smali, re.S):
        strings = dict(re.findall(r'const-string(?:/jumbo)? (v\d+), "([^"]*)"', block))
        call = re.search(r'invoke-direct \{v\d+, (v\d+)', block)
        if call and call.group(1) in strings:
            names.add(strings[call.group(1)])
    return names


def main(switch_path, mnomap_path, smali_path, output, carrier_config=None, epdg_conf=None):
    known = known_mnos(smali_path)
    volte = set()
    vowifi = set()
    for e in load(switch_path)['imsswitch']:
        name = e['mnoname']
        if name in known and e.get('enableIms') and e.get('enableServiceVolte'):
            volte.add(name)
            if e.get('enableServiceVowifi'):
                vowifi.add(name)

    plmns = {}
    for m in load(mnomap_path)['mnomap']:
        if any(m.get(k) for k in ('subset', 'gid1', 'gid2', 'spname')):
            continue
        mno = m['mnoname'].split(':')[0]
        if mno in volte:
            plmns.setdefault(m['mccmnc'], mno)

    root = ET.Element('CustomerData')
    general = ET.SubElement(root, 'GeneralInfo')
    nb = ET.SubElement(ET.SubElement(ET.SubElement(root, 'Settings'), 'IMSSetting'),
                       'NbSetting')
    for plmn, mno in sorted(plmns.items()):
        e = ET.SubElement(general, 'NetworkInfo')
        ET.SubElement(e, 'MCCMNC').text = plmn
        ET.SubElement(e, 'NetworkName').text = mno
    for mno in sorted(set(plmns.values())):
        s = ET.SubElement(nb, 'Setting')
        ET.SubElement(s, 'NetworkName').text = mno
        ET.SubElement(s, 'EnableIMS').text = 'true'
        ET.SubElement(s, 'EnableVoLTE').text = 'true'
        ET.SubElement(s, 'EnableVoLTEindicator').text = 'true'
        ET.SubElement(s, 'EnableVoiceoverWIFI').text = 'true' if mno in vowifi else 'false'
        ET.SubElement(s, 'EnableVideocall').text = 'false'
        ET.SubElement(s, 'EnableSMSoverIP').text = 'false'

    ET.indent(root)
    with open(output, 'wb') as f:
        f.write(b'<?xml version="1.0" encoding="utf-8"?>\n'
                b'<!-- Generated by gen_csc_from_imsswitch.py from imsswitch.json. -->\n')
        f.write(ET.tostring(root, encoding='utf-8'))
        f.write(b'\n')
    mnos = set(plmns.values())
    print('%d carriers with VoLTE (%d with VoWiFi), %d PLMNs'
          % (len(mnos), len(mnos & vowifi), len(plmns)))

    if carrier_config:
        wfc = vowifi_defaults(epdg_conf)
        update_carrier_config(carrier_config, sorted(
            (p, wfc.get(mno, wfc['default'])) for p, mno in plmns.items() if mno in vowifi))


WFC_BEGIN = '    <!-- VoWiFi carriers, generated by gen_csc_from_imsswitch.py. -->\n'
WFC_END = '    <!-- End of VoWiFi carriers. -->\n'


# Samsung's wifi_call_preferred -> ImsMmTelManager WIFI_MODE_*
WFC_MODES = {'1': 2, '2': 1, '3': 0}


def vowifi_defaults(path):
    """mnoname -> (Wi-Fi Calling on, framework mode or None) from <vowifi> entries."""
    out = {}
    for m in re.finditer(r'<vowifi\b(.*?)/>', open(path).read(), re.S):
        a = dict(re.findall(r'(\w+)\s*=\s*"([^"]*)"', m.group(1)))
        out.setdefault(a['mnoname'], (a.get('wifi_call_enable') == '1',
                                      WFC_MODES.get(a.get('wifi_call_preferred'))))
    return out


def update_carrier_config(path, plmns):
    text = open(path).read()
    if WFC_BEGIN in text:
        text = text[:text.index(WFC_BEGIN)] + text[text.index(WFC_END) + len(WFC_END):]
    blocks = []
    for plmn, (enabled, mode) in plmns:
        block = ('    <carrier_config mcc=%s mnc=%s>\n'
                 '        <boolean name="carrier_wfc_ims_available_bool" value="true" />\n'
                 '        <boolean name="carrier_default_wfc_ims_enabled_bool" value="%s" />\n'
                 % (quoteattr(plmn[:3]), quoteattr(plmn[3:]), 'true' if enabled else 'false'))
        if mode is not None:
            block += '        <int name="carrier_default_wfc_ims_mode_int" value="%d" />\n' % mode
        blocks.append(block + '    </carrier_config>\n')
    end = '</carrier_config_list>'
    i = text.rindex(end)
    text = text[:i] + WFC_BEGIN + ''.join(blocks) + WFC_END + text[i:]
    open(path, 'w').write(text)
    print('%s: Wi-Fi Calling on %d PLMNs' % (path, len(plmns)))


if __name__ == '__main__':
    if len(sys.argv) not in (5, 7):
        sys.exit(__doc__)
    main(*sys.argv[1:])
