#!/usr/bin/env python3
"""Generate a CSC customer.xml for com.sec.imsservice from Samsung's switch table.

Usage: gen_csc_from_imsswitch.py <imsswitch.json> <mnomap.json> <Mno.smali> <output>

This imsservice only takes its per-carrier IMS switches (EnableIMS,
EnableVoLTE, ...) from a CSC customer.xml; without one it turns VoLTE off.
Newer Samsung IMS builds keep these switches in the app itself
(res/raw/imsswitch.json). This turns that table into a customer.xml so the
switches do not depend on the phone's own CSC on /odm.

- One Setting per carrier with enableIms and enableServiceVolte that the
  imsservice code knows (Mno.smali), matched by plain MCCMNC from mnomap.json;
  MVNOs on the same MCCMNC match their host network's entry.
- VoLTE on, with IMS PS voice preferred on LTE. VoWiFi, video calls and SMS
  over IMS stay off: untested on this device.
- Voice/SS/USSD/emergency domains are left out, so imsservice uses its own
  per-carrier globalsettings.json values.
"""

import os
import re
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jsonc import load  # noqa: E402


def known_mnos(smali_path):
    smali = open(smali_path).read()
    names = set()
    for block in re.findall(r'new-instance v\d+, Lcom/sec/internal/ims/util/Mno;(.*?)sput-object',
                            smali, re.S):
        strings = dict(re.findall(r'const-string(?:/jumbo)? (v\d+), "([^"]*)"', block))
        call = re.search(r'invoke-direct \{v\d+, (v\d+)', block)
        if call and call.group(1) in strings:
            names.add(strings[call.group(1)])
    return names


def main(switch_path, mnomap_path, smali_path, output):
    known = known_mnos(smali_path)
    volte = set()
    for e in load(switch_path)['imsswitch']:
        name = e['mnoname']
        if name in known and e.get('enableIms') and e.get('enableServiceVolte'):
            volte.add(name)

    plmns = {}
    for m in load(mnomap_path)['mnomap']:
        if any(m.get(k) for k in ('subset', 'gid1', 'gid2', 'spname')):
            continue
        mno = m['mnoname'].split(':')[0]
        if mno in volte:
            plmns.setdefault(m['mccmnc'], mno)

    root = ET.Element('CustomerData')
    general = ET.SubElement(root, 'GeneralInfo')
    nb = ET.SubElement(ET.SubElement(ET.SubElement(root, 'Settings'), 'IMSSetting'),
                       'NbSetting')
    for plmn, mno in sorted(plmns.items()):
        e = ET.SubElement(general, 'NetworkInfo')
        ET.SubElement(e, 'MCCMNC').text = plmn
        ET.SubElement(e, 'NetworkName').text = mno
    for mno in sorted(set(plmns.values())):
        s = ET.SubElement(nb, 'Setting')
        ET.SubElement(s, 'NetworkName').text = mno
        ET.SubElement(s, 'EnableIMS').text = 'true'
        ET.SubElement(s, 'EnableVoLTE').text = 'true'
        ET.SubElement(s, 'EnableVoLTEindicator').text = 'true'
        ET.SubElement(s, 'EnableVoiceoverWIFI').text = 'false'
        ET.SubElement(s, 'EnableVideocall').text = 'false'
        ET.SubElement(s, 'EnableSMSoverIP').text = 'false'
        ET.SubElement(s, 'Voice_Domain_Preference_EUTRAN').text = 'imspsvoicepreferred'

    ET.indent(root)
    with open(output, 'wb') as f:
        f.write(b'<?xml version="1.0" encoding="utf-8"?>\n'
                b'<!-- Generated by gen_csc_from_imsswitch.py from imsswitch.json. -->\n')
        f.write(ET.tostring(root, encoding='utf-8'))
        f.write(b'\n')
    print('%d carriers with VoLTE, %d PLMNs' % (len(set(plmns.values())), len(plmns)))


if __name__ == '__main__':
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    main(*sys.argv[1:])
